//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

pub use super::telegram_chat_history::Entity as TelegramChatHistory;
pub use super::telegram_chat_queue::Entity as TelegramChatQueue;
pub use super::telegram_guest::Entity as TelegramGuest;
pub use super::telegram_guest_chat_history::Entity as TelegramGuestChatHistory;
pub use super::telegram_users::Entity as TelegramUsers;
pub use super::users::Entity as Users;
