//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "telegram_chat_queue")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub chat_history_id: i32,
    pub reply_threshold_in_seconds: i32,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::telegram_chat_history::Entity",
        from = "Column::ChatHistoryId",
        to = "super::telegram_chat_history::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TelegramChatHistory,
}

impl Related<super::telegram_chat_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramChatHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
