//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "telegram_guest")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub telegram_chat_id: i32,
    pub authorized: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::telegram_guest_chat_history::Entity")]
    TelegramGuestChatHistory,
}

impl Related<super::telegram_guest_chat_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramGuestChatHistory.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
