//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "telegram_guest_chat_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub telegram_guest_id: i32,
    pub message: String,
    pub created_at: DateTimeWithTimeZone,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    pub updated_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::telegram_guest::Entity",
        from = "Column::TelegramGuestId",
        to = "super::telegram_guest::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TelegramGuest,
}

impl Related<super::telegram_guest::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramGuest.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
