//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "telegram_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub telegram_chat_id: i32,
    pub user_id: Uuid,
    pub tier: String,
    pub daily_limit: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub profile_summary: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub chat_summary: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::telegram_chat_history::Entity")]
    TelegramChatHistory,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::telegram_chat_history::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramChatHistory.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
