//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "telegram_chat_history")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub author: String,
    pub telegram_user_id: i32,
    #[sea_orm(column_type = "Text")]
    pub message: String,
    pub session_id: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: Option<DateTimeWithTimeZone>,
    pub deleted_at: Option<DateTimeWithTimeZone>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::telegram_chat_queue::Entity")]
    TelegramChatQueue,
    #[sea_orm(
        belongs_to = "super::telegram_users::Entity",
        from = "Column::TelegramUserId",
        to = "super::telegram_users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TelegramUsers,
}

impl Related<super::telegram_chat_queue::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramChatQueue.def()
    }
}

impl Related<super::telegram_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
