//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub fullname: String,
    #[sea_orm(unique)]
    pub username: String,
    pub email: Option<String>,
    #[sea_orm(unique)]
    pub phone_number: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub password_hash: Option<Vec<u8>>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)", nullable)]
    pub password_salt: Option<Vec<u8>>,
    pub password_iteration: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::telegram_users::Entity")]
    TelegramUsers,
}

impl Related<super::telegram_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
